repo_url: https://github.com/vitorfleonardo/VerificaAAA.git
repo_name: VerificaAAA

site_name: VerificAAA

theme:
  name: readthedocs

 
  
  
 

markdown_extensions:
  - def_list
  

nav:
- Início: "index.md"
- Checklist:
  - Desenvolvimento Web: "desenvolvimento/primeiro.md"

